-- MS SQL Server Solution --

-- Script 2 --
SELECT CAST(ROUND(SUM(LAT_N), 2) AS NUMERIC(8,2)), CAST(ROUND(SUM(LONG_W), 2) AS NUMERIC(8, 2)) FROM STATION;

-- Script 13 --
SELECT CAST(ROUND(SUM(LAT_N), 4) AS NUMERIC(36, 4)) FROM STATION WHERE (LAT_N > 38.7880) AND (LAT_N < 137.2345);

-- Script 14 --
SELECT CAST(ROUND(MAX(LAT_N), 4) AS NUMERIC(36, 4)) FROM STATION WHERE (LAT_N < 137.2345);

-- Script 15 --
DECLARE @max_lat_n AS FLOAT = (SELECT MAX(LAT_N) FROM STATION WHERE (LAT_N < 137.2345))
SELECT CAST(ROUND(LONG_W, 4) AS NUMERIC(36, 4)) FROM STATION WHERE (LAT_N < 137.2345) AND LAT_N = @max_lat_n;

-- Script 16 --
SELECT CAST(ROUND(MIN(LAT_N), 4) AS NUMERIC(36, 4)) FROM STATION WHERE (LAT_N > 38.7780);

-- Script 17 --
DECLARE @min_lat_n AS FLOAT = (SELECT MIN(LAT_N) FROM STATION WHERE (LAT_N > 38.7780))
SELECT CAST(ROUND(LONG_W, 4) AS NUMERIC(36, 4)) FROM STATION WHERE LAT_N = @min_lat_n;

-- Script 18 --
SELECT CAST(ROUND(MAX(LAT_N) - MIN(LAT_N) + MAX(LONG_W) - MIN(LONG_W), 4) AS NUMERIC(36, 4)) FROM STATION;

-- Script 19 --
SELECT CAST(ROUND(SQRT(POWER(MAX(LAT_N) - MIN(LAT_N), 2) + POWER(MAX(LONG_W) - MIN(LONG_W), 2)), 4) AS NUMERIC(36, 4)) FROM STATION;

-- Script 20 --
DECLARE @count AS INT = (SELECT COUNT(*) FROM STATION);

SELECT CAST(ROUND(AVG(1.0 * LAT_N), 4) AS NUMERIC(36, 4))
FROM (
    SELECT LAT_N FROM STATION
     ORDER BY LAT_N
     OFFSET (@count - 1) / 2 ROWS
     FETCH NEXT 1 + (1 - @count % 2) ROWS ONLY
) AS median;